#
###################################
# Site wide configuration
####################################
#
title: Bufan Zheng
email: whuzbf@qq.com
description: Bufan Zheng's blog,powered by jekyll.
url: https://whuzbf.github.io # the base hostname & protocol for your site
keywords: ["jekyll", "physics", "math","blog"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Shanghai
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  math_engine: mathjax
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

# Pagination
paginate: 5
paginate_path: 'home/page:num'

plugins:
  - jekyll-gist
  - jemoji
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-paginate

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Bufan Zheng (郑卜凡)
  avatar: bufan.jpg
  job: "Student at WHU"
  bio: "Phyiscs lover and Code fancier. Studying in Wuhan, China."
  email: whuzbf@qq.com
  disqus-shortname: #username
  twitter:  #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: WHUZBF #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: dodozbf
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
  rss: true
  zhihu: zheng-bu-fan-78-55
